// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using review_jogos_steam.Data;

#nullable disable

namespace review_jogos_steam.Migrations
{
    [DbContext(typeof(ReviewDbContext))]
    [Migration("20231124153826_testezin")]
    partial class testezin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("JogoTag", b =>
                {
                    b.Property<int>("JogoIdJogo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsIdTag")
                        .HasColumnType("INTEGER");

                    b.HasKey("JogoIdJogo", "TagsIdTag");

                    b.HasIndex("TagsIdTag");

                    b.ToTable("JogoTag");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JogoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nota")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("JogoID");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvaliacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coment")
                        .HasColumnType("TEXT");

                    b.HasKey("IdComentario");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Conquista", b =>
                {
                    b.Property<int>("IdConquista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JogoIdJogo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdConquista");

                    b.HasIndex("JogoIdJogo");

                    b.ToTable("Conquista");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Desenvolvedor", b =>
                {
                    b.Property<int>("IdDesenvolvedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDesenvolvedor");

                    b.ToTable("Desenvolvedor");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdGenero");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Imagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("IdImagem");

                    b.HasIndex("JogoId");

                    b.ToTable("Imagem");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Jogo", b =>
                {
                    b.Property<int>("IdJogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DesenvolvedorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlataformaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdJogo");

                    b.HasIndex("DesenvolvedorId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("PlataformaId");

                    b.ToTable("Jogo");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Plataforma", b =>
                {
                    b.Property<int>("IdPlataforma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPlataforma");

                    b.ToTable("Plataforma");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Tag", b =>
                {
                    b.Property<int>("IdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTag");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("JogoTag", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoIdJogo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("review_jogos_steam.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsIdTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("review_jogos_steam.Models.Avaliacao", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Jogo", "Jogo")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("JogoID");

                    b.HasOne("review_jogos_steam.Models.Usuario", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Comentario", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Avaliacao", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("AvaliacaoId");

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Conquista", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Jogo", null)
                        .WithMany("Conquistas")
                        .HasForeignKey("JogoIdJogo");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Imagem", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Jogo", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Desenvolvedor", "Desenvolvedor")
                        .WithMany("Jogos")
                        .HasForeignKey("DesenvolvedorId");

                    b.HasOne("review_jogos_steam.Models.Genero", "Genero")
                        .WithMany("Jogos")
                        .HasForeignKey("GeneroId");

                    b.HasOne("review_jogos_steam.Models.Plataforma", "Plataforma")
                        .WithMany("Jogos")
                        .HasForeignKey("PlataformaId");

                    b.Navigation("Desenvolvedor");

                    b.Navigation("Genero");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Desenvolvedor", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Genero", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Jogo", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Conquistas");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Plataforma", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
