// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using review_jogos_steam.Data;

#nullable disable

namespace review_jogos_steam.Migrations
{
    [DbContext(typeof(ReviewDbContext))]
    partial class ReviewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("review_jogos_steam.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nota")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAvaliacao");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JogoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdComentario");

                    b.HasIndex("JogoId");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Conquista", b =>
                {
                    b.Property<int>("IdConquista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdConquista");

                    b.HasIndex("JogoId");

                    b.ToTable("Conquista");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Desenvolvedor", b =>
                {
                    b.Property<int>("IdDesenvolvedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDesenvolvedor");

                    b.ToTable("Desenvolvedor");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdGenero");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Imagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdImagem");

                    b.ToTable("Imagem");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DevIdDesenvolvedor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GenIdGenero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlatIdPlataforma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("imgIdImagem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DevIdDesenvolvedor");

                    b.HasIndex("GenIdGenero");

                    b.HasIndex("PlatIdPlataforma");

                    b.HasIndex("imgIdImagem");

                    b.ToTable("Jogo");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Plataforma", b =>
                {
                    b.Property<int>("IdPlataforma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPlataforma");

                    b.ToTable("Plataforma");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Tag", b =>
                {
                    b.Property<int>("IdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTag");

                    b.HasIndex("JogoId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Comentario", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Jogo", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("JogoId");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Conquista", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Jogo", null)
                        .WithMany("Conq")
                        .HasForeignKey("JogoId");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Jogo", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Desenvolvedor", "Dev")
                        .WithMany()
                        .HasForeignKey("DevIdDesenvolvedor");

                    b.HasOne("review_jogos_steam.Models.Genero", "Gen")
                        .WithMany()
                        .HasForeignKey("GenIdGenero");

                    b.HasOne("review_jogos_steam.Models.Plataforma", "Plat")
                        .WithMany()
                        .HasForeignKey("PlatIdPlataforma");

                    b.HasOne("review_jogos_steam.Models.Imagem", "img")
                        .WithMany()
                        .HasForeignKey("imgIdImagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dev");

                    b.Navigation("Gen");

                    b.Navigation("Plat");

                    b.Navigation("img");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Tag", b =>
                {
                    b.HasOne("review_jogos_steam.Models.Jogo", null)
                        .WithMany("Tags")
                        .HasForeignKey("JogoId");
                });

            modelBuilder.Entity("review_jogos_steam.Models.Jogo", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Conq");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
